### ISSUE TITLE
illegal argument exception with SignalClient

### ISSUE THREAD

**Issue by waater** [ptgoetz/storm-signals#6]
```SignalClient sc = new SignalClient("xx.xx.xx.xx:2181", "spout");```

gives a 
```
Exception in thread "main" java.lang.IllegalArgumentException: Path must start with / character
	at org.apache.curator.utils.PathUtils.validatePath(PathUtils.java:54)
	at org.apache.curator.utils.PathUtils.validatePath(PathUtils.java:37)
	at org.apache.curator.utils.ZKPaths.fixForNamespace(ZKPaths.java:63)
	at org.apache.curator.framework.imps.NamespaceImpl.fixForNamespace(NamespaceImpl.java:82)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.fixForNamespace(CuratorFrameworkImpl.java:574)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:139)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:36)
	at backtype.storm.contrib.signals.client.SignalClient.send(SignalClient.java:36)
	at storm.signalclient.TestSignalClient.main(TestSignalClient.java:11)

```

this is contrary to the README usage example. 
I did try adding /, did not help.

**Comment by L3O** [comment]
Any update on this ?

**Comment by itsmkj** [comment]
Just replace this.name with "/"+ this.name everywhere the path is used
